In [13]:
import keras
#downloading images from 0-9 and are encoded as Numpy arrays
from keras.datasets import mnist


In [73]:
#train_image and train_label are the training set 
#test_image and test_lanbels are the testing set
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [74]:
train_images.shape

(60000, 28, 28)

In [76]:
from keras import models
from keras import layers

network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

In [75]:
print(train_images)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [82]:
train_images.shape

(60000, 784)

In [83]:
len(train_lables)

2

In [85]:
test_images.shape

(10000, 784)

In [87]:
len(test_lables)

NameError: name 'test_lables' is not defined

In [86]:
test_lables

NameError: name 'test_lables' is not defined

In [88]:
train_lables

(array([[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        ...,
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],

In [89]:
# network consist of two dense layers which are densly connected called Fully Connected
# the second layer is a 10-way softmax layer, which means it will be return an array of 
# 10 probability scores
# each score will be the prob that the current digit image belongs to 0-9 digit classes

network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

In [90]:
#making the netowrk ready for training by inputing the compilation step 
#loss function, optimizer, and accurary 

network.compile(optimizer = 'rmsprop', 
               loss = 'categorical_crossentropy', 
               metrics = ['accuracy'])

In [95]:
#preprocess the data by reshaping it into the shape the network expects and scaling to so 
#all values are in the 0-1 interval 

train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [97]:
# categorically encode the labels

from keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [103]:
network.fit(train_images, train_labels, epochs = 4, batch_size = 128)

Epoch 1/4
60000/60000 [==============================] - 3s 47us/step - loss: 2.3013 - accuracy: 0.1124
Epoch 2/4
60000/60000 [==============================] - 3s 45us/step - loss: 2.3013 - accuracy: 0.1124
Epoch 3/4
60000/60000 [==============================] - 3s 45us/step - loss: 2.3013 - accuracy: 0.1124
Epoch 4/4
60000/60000 [==============================] - 3s 47us/step - loss: 2.3013 - accuracy: 0.1124


In [104]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print(test_acc)

10000/10000 [==============================] - 0s 33us/step
0.11349999904632568


In [ ]:
# didnt perform well at all 
# with accuracy of 11.35% 
